-- SQL script to delete all cases and insert only the Dean Tran case
-- Run this in your Supabase SQL editor

-- First, delete all related data (cascade should handle this, but being explicit)
DELETE FROM case_factors;
DELETE FROM case_holdings;
DELETE FROM case_citations;
DELETE FROM case_analysis_metadata;

-- Delete all cases
DELETE FROM court_cases;

-- Insert the Dean Tran case
INSERT INTO court_cases (
    case_name,
    docket_number,
    citation,
    court_type,
    court_name,
    decision_date,
    published_date,
    opinion_text,
    opinion_url,
    judges,
    case_type,
    topics,
    source,
    source_url,
    is_published,
    is_downloaded
) VALUES (
    'DEAN TRAN vs. COMMONWEALTH',
    'SJC-13641',
    NULL, -- No standard citation format found in the text
    'SJC',
    'Supreme Judicial Court',
    '2025-09-10', -- Using the end date from the date range
    '2025-05-07', -- Using the start date as published date
    $OPINION_TEXT$DEAN TRAN vs. COMMONWEALTH
Docket:	SJC-13641
Dates:	May 7, 2025 - September 10, 2025
Present:	Suffolk
County:	Budd, C.J., Gaziano, Kafker, Wendlandt, Georges, & Wolohojian, JJ.
Keywords:	General Court. Constitutional Law, General Court, Separation of powers. Practice, Criminal, Immunity from prosecution, Conduct of prosecutor, Interlocutory appeal, Grand jury proceedings, Dismissal. Conflict of Interest. Grand Jury. Supreme Judicial Court, Superintendence of inferior courts.
            Civil action commenced in the Supreme Judicial Court for the county of Suffolk on March 6, 2024.

            The case was reported by Wolohojian, J.

            Michael Walsh (John H. Walsh also present) for the petitioner.

            Tara L. Johnston, Assistant Attorney General (Kristen Sullivan, Assistant Attorney General, also present) for the Commonwealth.

            WOLOHOJIAN, J.  The defendant, who served as a State senator from 2017 until 2020, was indicted on two counts of using his official position to secure unwarranted privileges by drawing on public resources, including members of his Senate staff, for his reelection campaigns.[1]  See G. L. c. 268A, §§ 23 (b) (2) (ii), 26.  He moved to dismiss the charges on various grounds, and after that motion was denied by a Superior Court judge, he sought interlocutory review pursuant to G. L. c. 211, § 3.  His petition asserted, among other things, that (1) he is entitled to legislative immunity under art. 21 of the Massachusetts Declaration of Rights (deliberation, speech, and debate); (2) the indictments violate separation of powers principles reflected in Part II, c. 1, § 3, arts. 10 and 11 of the Constitution of the Commonwealth (art. 10 and art. 11) because only the Legislature may regulate and punish the conduct of legislators; and (3) the prosecutor exceeded her authority when she excluded from deliberation and without court approval a grand juror who appeared to express possible political bias against the defendant.[2]  The single justice reserved and reported the matter, raising the additional question "whether a criminal defendant who has moved to dismiss the charges against him based on a claim of immunity, including legislative immunity, is entitled to interlocutory review of the denial of that motion to dismiss and, if so, whether such interlocutory review is to be sought from the Appeals Court under the doctrine of present execution, or by way of a petition pursuant to G. L. c. 211, § 3." 

            We conclude that G. L. c. 211, § 3, is the correct procedural mechanism by which to obtain interlocutory review of the denial of a motion to dismiss based on a claim of legislative immunity from criminal prosecution.  We also conclude that the defendant is not immune from prosecution with respect to the indictments at issue here either under art. 21 of the Massachusetts Declaration of Rights or separation of powers principles under art. 10 and art. 11.  Finally, we conclude that even though the prosecutor overstepped her authority in excusing a grand juror for bias without judicial involvement, the defendant was not prejudiced because excusing a juror who harbored an apparent bias against the defendant was protective of the defendant''s interests, and there remained a full complement of grand jurors necessary to consider whether to return the indictments.  For these reasons, the judge correctly denied the motion to dismiss, and we remand this case to the county court for entry of a judgment denying the defendant''s petition for extraordinary relief.

            Background.  We summarize the agreed-upon facts, reserving additional details for later discussion. 

            The defendant was elected to the State Senate in a special election in 2017, won reelection in 2018, and lost reelection in 2020.  In October 2019, the Senate president received two anonymous letters regarding the defendant''s misuse of Senate staff for his 2018 reelection campaign.  The Senate president referred the allegations to the Senate committee on ethics (Senate ethics committee), which then conducted a formal investigation and issued a final report.

            The parties have agreed that

"[the Senate ethics committee] found that during the defendant''s 2018 re-election, the defendant''s staff did campaign work during regular Senate business hours with the defendant''s knowledge.  Additionally, the [Senate ethics committee] found that the defendant continued to expect his staff to do campaign work for his 2020 re-election campaign.  The [Senate ethics committee] also determined that the defendant asked his staff to engage in inappropriate fundraising work for his 2018 campaign, ignored repeated advice from Senate [h]uman [r]esources, [the Office of Senate Counsel], and others that it was inappropriate for staff to do campaign work during regular business hours and to participate in most fundraising activities, and did not take any corrective steps at any point.  The [Senate ethics committee] found that the defendant had violated State Senate Rule 10A which prohibits members from employing with [S]tate funds anyone who ''does not perform tasks which contribute to the work of the Senate'' or whose tasks are not ''commensurate with the compensation received.''  The [Senate ethics committee] also concluded that the defendant likely violated various sections of the conflict-of-interest and campaign-finance laws.  The [Senate ethics committee] recommended that, for the remainder of the 2019-2020 legislative session, the defendant be removed from his position as Assistant Minority Whip and segregated from his staff, and that his office be relocated to another available space in the State House."  (Proper name substituted with "the defendant" throughout; citations omitted.)

            The Senate ethics committee''s report was later referred to the State Ethics Commission and to the Office of Campaign and Political Finance (OCPF).  Following its own investigation, OCPF referred the matter to the Attorney General''s office, and the Attorney General presented the matter to the grand jury. 

            Over the course of eleven days, the grand jury heard testimony from several witnesses, six of whom were former members of the defendant''s Senate staff.  Those staff members provided testimony that was consistent with, and supported, the conclusions and findings of the Senate ethics committee as set out above.  In addition to hearing testimony, the grand jury received many e-mail and text message exchanges involving the defendant and his staff.  These documents also were consistent with the conclusions and findings of the Senate ethics committee. 

            Ultimately, the grand jury returned two indictments against the defendant for using an official position to secure unwarranted privileges in violation of G. L. c. 268A, §§ 23 (b) (2) (ii) and 26.  The first indictment alleges that the defendant "utilize[d] public resources, including members of his Massachusetts State Senate staff" for his 2018 reelection campaign.  The second indictment alleges the same with respect to the defendant''s 2020 reelection campaign. 

            The defendant moved to dismiss the indictments on the grounds, among others,[3] that he is immune from prosecution under art. 21, and pursuant to separation of powers principles under art. 10 and art. 11.  The defendant later supplemented his motion and contended that the prosecutor impaired the grand jury proceedings by excluding a grand juror from the decision whether to indict him.  A judge of the Superior Court rejected the defendant''s claim of legislative immunity, reasoning that immunity under art. 21 does not extend to the conduct charged in the indictments, and the statutorily authorized criminal prosecution of the defendant does not interfere with the Legislature in violation of the separation of powers.  The judge further determined that the prosecutor''s exclusion of the grand juror did not warrant dismissal of the indictments because the defendant failed to demonstrate prejudice or that the removal of the grand juror adversely affected the independence of the grand jury.  After the judge denied the motion to dismiss, the defendant filed a petition pursuant to G. L. c. 211, § 3, in the county court seeking interlocutory review.  The single justice reserved and reported the matter to the full court.

            Discussion.  1.  Interlocutory review of legislative immunity claim.  We have not previously had occasion to consider whether claims of immunity in criminal cases are subject to interlocutory review under G. L. c. 211, § 3, or whether, as in civil cases, claims of immunity are to be appealed on an interlocutory basis to the Appeals Court under the doctrine of present execution.  We conclude that interlocutory review of the denial of a motion to dismiss based on a claim of legislative immunity from criminal prosecution is to be sought by way of a petition under G. L. c. 211, § 3.4  See Fabre v. Walton, 436 Mass. 517, 522 (2002), S.C., 441 Mass. 9 (2004), quoting Zullo v. Goguen, 423 Mass. 679, 681 (1996) ("This court has ''wide discretion in devising various procedures for the course of appeals in different classes of cases''").

            In criminal cases, there is ordinarily "no right to interlocutory review of the denial of a motion to dismiss pursuant to G. L. c. 211, § 3," Flood v. Commonwealth, 465 Mass. 1015, 1016 (2013), because "the rights of criminal defendants are generally fully protected through the regular appellate process," Costarelli v. Commonwealth, 374 Mass. 677, 679 (1978).  However, we have carved out a limited exception to this general rule in cases raising a double jeopardy claim of substantial merit.  See Quigley v. Commonwealth, 480 Mass. 1026, 1026 (2018).  Where a defendant presses such a claim, he or she is "entitled to review under our general superintendence power" because the right not to be tried twice for the same offense "would be seriously weakened if appellate review of a claim of double jeopardy were delayed until after a second trial."  Costarelli, 374 Mass. at 680.  The exception is animated by the principle that "the double jeopardy right is a right not to be tried" and, therefore, appellate review after trial and conviction would be inadequate were the defendant to prevail on his double jeopardy claim.  Flood, 465 Mass. at 1016.

            Demonstrating the limited nature of the exception, we have "consistently rejected attempts to obtain interlocutory review as a matter of right under G. L. c. 211, § 3, of denials of motions to dismiss" on bases that are not "analog[ous] to double jeopardy claims."  Cabrera v. Commonwealth, 496 Mass. 179, 183 (2025), quoting Soucy v. Commonwealth, 470 Mass. 1025, 1026 (2015).  See, e.g., Quigley, 480 Mass. at 1026-1027 & n.1 (petitioner not entitled to interlocutory review under G. L. c. 211, § 3, of claim that police failed to timely file citations for motor vehicle offenses, as required by statute, because claim did not involve right not to be tried); N.M. v. Commonwealth, 478 Mass. 89, 92 (2017) (loss of privacy protections afforded to juveniles did not entitle juvenile who had been indicted as youthful offender to interlocutory review under G. L. c. 211, § 3, because claim did not implicate right not to be tried); Garden v. Commonwealth, 460 Mass. 1018, 1019 (2011), quoting Ackerman v. Commonwealth, 445 Mass. 1025, 1025 (2006) (petitioner not entitled to interlocutory review under G. L. c. 211, § 3, of statute of limitations defense because defense was "unlike a double jeopardy claim, which vindicates ''the right not to be tried at all''").

            The question here, therefore, is whether a substantial claim of legislative immunity is sufficiently analogous to double jeopardy such that it should be entitled to interlocutory review under G. L. c. 211, § 3.  We believe that it is because - like double jeopardy -- legislative immunity is not simply a defense against criminal liability but implicates a right not to be tried at all.  See Coffin v. Coffin, [4] Mass. 1, 27 (1808) (legislative immunity provided under art. 21 enables "representatives to execute the functions of their office without fear of prosecutions, civil or criminal").  For this reason, appellate review after trial and conviction would be inadequate were the defendant ultimately to prevail on his claim of legislative immunity.

            The United States Supreme Court has considered the availability of interlocutory review of legislative immunity claims under the Federal collateral order doctrine, and reached a similar conclusion for similar reasons.  See Patel v. Martin, 481 Mass. 29, 34 (2018) (discussing collateral order doctrine).  The Court has concluded that claims of legislative immunity under the Federal speech or debate clause implicate a right not to be tried, Midland Asphalt Corp. v. United States, 489 U.S. 794, 801 (1989), and are immediately appealable under the collateral order doctrine, just as are double jeopardy claims, Lauro Lines s.r.l. v. Chasser, 490 U.S. 495, 499 (1989) (because "the deprivation of a right not to be tried is effectively unreviewable after final judgment," it "is immediately appealable").  Although we are not bound by the Federal decisions, their reasoning is consistent with ours in allowing interlocutory review of double jeopardy claims and, by analogy, of claims of legislative immunity from criminal prosecution.

            The defendant takes the position that claims of legislative immunity from criminal prosecution should be directed to the Appeals Court under the doctrine of present execution, even though he himself sought interlocutory review under G. L. c. 211, § 3.[5]  Although the doctrine of present execution allows some types of interlocutory orders to be immediately appealed to the Appeals Court "as a matter of right," Elles v. Zoning Bd. of Appeals of Quincy, 450 Mass. 671, 673-674 (2008), the doctrine applies "only in very limited circumstances," where "the interlocutory ruling ''will interfere with rights in a way that cannot be remedied on appeal'' from the final judgment, and where the matter is ''collateral'' to the merits of the controversy," Id. at 674, quoting Maddocks v. Ricker, 403 Mass. 592, 597-600 (1988).

            The doctrine of present execution has been applied in a variety of civil cases where there is an assertion of immunity,[6] but the defendant has not identified a single criminal case in which it has been applied.  And we see no benefit to creating a new procedural appellate pathway for the extremely limited number of cases calling for interlocutory review where a defendant claims legislative immunity from criminal prosecution.  Instead, allowing all such claims to follow a single route to interlocutory review will promote predictability and development of a uniform body of law.  Cf. Fabre, 436 Mass. at 522 (concluding that, for purposes of consistent treatment of SLAPP suits, interlocutory review from denial of special motion to dismiss filed pursuant to anti-SLAPP statute should be pursued in Appeals Court rather than through "different avenues of appeal"); Department of Revenue v. Jarvenpaa, 404 Mass. 177, 181 (1989) (conclusion that "appeals in G. L. c. 209C cases should go to the same court" supported by "[p]ractical considerations" of "[u]niformity of treatment of litigants and the development of a consistent body of law").

            For these reasons, we conclude that interlocutory review of the denial of a motion to dismiss based on a substantial claim of legislative immunity from criminal prosecution is to be pursued under G. L. c. 211, § 3, because legislative immunity, like double jeopardy, implicates a right not to be tried and is not merely a shield against criminal liability.  See Kimbroughtillery v. Commonwealth, 471 Mass. 507, 509 n.5 (2015) ("Because the petitioner''s claim is so closely identified with double jeopardy, a petition for relief under G. L. c. 211, § 3, is the appropriate avenue for review").  The doctrine of present execution is not the proper path by which to obtain such review.

            2.  Immunity from prosecution.  Section 23 of the conflict of interest statute, G. L. c. 268A, §§ 1 et seq., establishes additional standards of conduct for "all [S]tate, county, and municipal employees," G. L. c. 268A, § 23 (a), a group that is defined to include elected members of the General Court, G. L. c. 268A, § 1 (q).  As pertinent here, the defendant is alleged to have violated § 23 (b) (2) (ii) of the act, which provides that no person within the scope of the statute

"shall knowingly, or with reason to know . . . use or attempt to use [his or her] official position to secure for such officer, employee or others unwarranted privileges or exemptions which are of substantial value and which are not properly available to similarly situated individuals."

A violation of § 23 (b) (2) may result in criminal penalties where the violation is committed with "fraudulent intent" and "the unwarranted privileges or exemptions have a fair market value in the aggregate of more than $1,000 in any [twelve] month period."  G. L. c. 268A, § 26.  See Commonwealth v. Spaulding, 495 Mass. 300, 305 (2025).  The indictments at issue here charge the defendant with obtaining unwarranted privileges with fraudulent intent by "utiliz[ing] public resources, including members of his Massachusetts State Senate staff" for his 2018 and 2020 reelection campaigns.[7] 

            The defendant contends that he is immune from prosecution for violating the conflict of interest statute.  He rests this argument on three articles of the Massachusetts Constitution.  First, he argues that he is immune from prosecution by virtue of art. 21 of the Declaration of Rights, which provides that

"[t]he freedom of deliberation, speech and debate, in either house of the legislature, is so essential to the rights of the people, that it cannot be the foundation of any accusation or prosecution, action or complaint, in any other court or place whatsoever."

 

As to art. 21, the defendant argues that he has absolute immunity from criminal prosecution for speech and debate, which he contends includes an absolute privilege to direct his Senate staff as he wishes.

            Second, he argues that he is immune from prosecution under Part II, c. 1, § 3, art. 11, of the Constitution of the Commonwealth, which gives to the Senate the same powers and authority as are given to the House of Representatives under Part II, c. 1, § 3, art. 10, to wit:[8]

"The [Senate] shall be the judge of the returns, elections, and qualifications of its own members, as pointed out in the [C]onstitution; shall choose their own speaker; appoint their own officers, and settle the rules and orders of proceeding in their own house."

In addition, art. 11 provides that both houses

"may try, and determine, all cases where their rights and privileges are concerned, and which, by the constitution, they have authority to try and determine, by committees of their own members, or in such other way as they may respectively think best."

The defendant argues that criminal prosecution by the executive branch, in front of the judiciary, violates the separation of powers principle reflected in arts. 10 and 11 because those articles make each chamber "the judge of the returns, elections, and qualifications of its own members" and give them the power to "try, and determine, all cases where their rights and privileges are concerned."[9]

            Because the issue whether the defendant is entitled to immunity from prosecution presents a question of law, our review is de novo.  See Commonwealth v. Sullivan, 492 Mass. 36, 42 (2023).

            a.  Article 21 -- deliberation, speech, and debate.  This court has only once before examined the meaning and scope of legislative privilege for deliberation, speech, and debate under art. 21.  We therefore begin our discussion with a close examination of that seminal case, Coffin, 4 Mass. 1, which was decided not long after the adoption of the Massachusetts Constitution.

            William Coffin sued Micajah Coffin for "maliciously uttering and publishing defamatory words," specifically, that William had committed a felony by robbing the Nantucket Bank.  Coffin, 4 Mass. at 23.  The facts were as follows.  Micajah and Benjamin Russell were members of the House of Representatives, with Micajah representing the town of Nantucket.  While the House was in session, Russell (who had some acquaintance with William and thought highly of him) laid a resolution on the table to have William appointed as a notary for Nantucket.  Id. at 24.  Micajah asked Russell where he had obtained the information about William upon which the resolution was moved.  Russell answered, "from a respectable gentleman from Nantucket."  Id.  The resolution then passed, and the speaker of the House took up other business.  "Russell then left his place, and was standing in the passage-way, within the room, conversing with several gentlemen" (emphasis added).  Id.  Micajah approached Russell and asked who the "respectable gentleman" was from whom Russell had received the information he had communicated to the House in support of the resolution.  Id.  Russell "answered carelessly, [']he was perhaps one of his relations,['] and named Coffin, as most of the Nantucket people were of that name."  Id.  Russell then pointed to William, who was sitting in the chamber, and Micajah asked, "What, that convict?"

"Russell, surprised at the question, asked the defendant what he meant; he replied, ''Don''t thee know the business of Nantucket Bank?''  [Russell] said, ''Yes, but he was honorably acquitted.''  [Micajah] then said, ''That did not make him less guilty, thee knows.''" 

Id. at 24-25.  The case was tried to a jury, and Micajah was found liable for defamation.

            On appeal, Micajah argued that he was immune from liability under art. 21 at the time he spoke the words that were the basis for the defamation claim because "he and Benjamin Russell were members of the House of Representatives, then in session, and that he spoke the words to Russell, in deliberation in the house, concerning the appointment of a notary public, and that the words had relation to the subject of their deliberation."  Coffin, 4 Mass. at 24.  To decide this argument, the court began by considering whether the rights secured by art. 21 were held individually by the members or institutionally by the houses.  The court concluded that the privilege secured by art. 21 "is not so much the privilege of the house, as an organized body, as of each individual member composing it, who is entitled to this privilege, even against the declared will of the house."  Id. at 27.  The court drew this conclusion from the principle that the privilege was "derive[d] from the will of the people, expressed in the [C]onstitution, which is paramount to the will of either or both branches of the [L]egislature."  Id.  Having concluded that the rights secured by art. 21 are held by individual members, and not by the houses, it followed, in the court''s view, that members cannot be deprived of those rights either "by a resolve of the house or by an act of the [L]egislature."  Id.

            The court then turned to considering the purpose and scope of art. 21 and, in an often-quoted passage expressing a broad construction of the legislative privilege, stated:

"The[] privileges [of art. 21] are thus secured, not with the intention of protecting the members against prosecutions for their own benefit, but to support the rights of the people, by enabling their representatives to execute the functions of their office without fear of prosecutions, civil or criminal.  [We] therefore think that the article ought not to be construed strictly, but liberally, that the full design of it may be answered.  [We] will not confine it to delivering an opinion, uttering a speech, or haranguing in debate; but will extend it to the giving of a vote, to the making of a written report, and to every other act resulting from the nature, and in the execution, of the office; and [we] would define the article as securing to every member exemption from prosecution, for every thing said or done by him, as a representative, in the exercise of the functions of that office, without inquiring whether the exercise was regular according to the rules of the house, or irregular and against their rules.  [We] do not confine the member to his place in the house; and [we are] satisfied that there are cases in which he is entitled to this privilege, when not within the walls of the representatives'' chamber."

Coffin, 4 Mass. at 27.  The court then considered whether art. 21 was confined to speech on the floor of the House or whether it extended protection to a member when sitting in committee, and concluded that the member should "be protected from civil or criminal prosecutions for every thing said or done by him in the exercise of his functions, as a representative, in committee, either in debating, in assenting to, or in draughting a report."  Id. at 28.

            Although it reached a generous construction of art. 21, the court also emphasized that the scope of the legislative privilege -- while broad -- was neither absolute nor unlimited.  Instead, the court held that availability of the right turned on whether the representative was acting in his capacity as a member of the House while carrying out the duties of his office.  "When a representative is not acting as a member of the house, he is not entitled to any privileges above his fellow-citizens."  Coffin, 4 Mass. at 28.  Put otherwise, "it must appear that some language or conduct of his, in the character of a representative, is the foundation of the prosecution, for in no other character can he claim the privilege."  Id. at 31.  If a member is being prosecuted for nonlegislative conduct, "that [offense] against law may be duly and seasonably punished, [because] this privilege is not extended to arrests on criminal prosecutions, in any case where by law the member may be prosecuted as a criminal."  Id. at 29.

            Having laid out a broad -- but not unlimited -- understanding of the scope and purpose of art. 21, the court concluded that Micajah''s statements to Russell -- despite having been made within the House on a topic placed before it for resolution -- were not protected by art. 21, and affirmed the finding of liability against Micajah for defamation.

            We have not had occasion to construe or apply art. 21 since Coffin.  Nor have we interpreted or applied the statements, principles, or holdings of Coffin since it was decided.  That said, the case has not gone dormant.  Instead, it has served as the foundation for the United States Supreme Court''s jurisprudence regarding the speech or debate clause of art. I, § 6, of the United States Constitution, despite the difference in language between the two.[10]  Indeed, in 1880, the Court recognized Coffin as "perhaps, the most authoritative case in this country on the construction of the provision in regard to freedom of debate in legislative bodies, and being so early after the formation of the Constitution of the United States, is of much weight."  Kilbourn v. Thompson, 103 U.S. 168, 204 (1880).  See Abuzahra v. Cambridge, 101 Mass. App. Ct. 267, 272 (2022) ("the United States Supreme Court has looked to [our construction of art. 21 in Coffin] in interpreting the Federal clause"). 

            In interpreting and applying art. 21, we are not bound by the Supreme Court''s interpretation and application of the Federal speech or debate clause.  Nonetheless, the Supreme Court''s decisions are of interest to us for two reasons.  First, as we have noted, they rest upon the foundation laid in Coffin regarding the scope of legislative immunity for deliberation, speech, and debate, and have adopted Coffin''s central holding that the privilege extends only to legislative acts.  Second, they provide examples of how the principles first laid down in Coffin have been applied to various subsequent circumstances.  For these reasons, we turn to the Supreme Court''s decisions now. 

            In Kilbourn, 103 U.S. 168, involving a claim for false imprisonment based on the arrest of the sergeant-at-arms of the House of Representatives, the Court adopted the reasoning of Coffin, and held that the Federal speech or debate clause (Clause) applies "to things generally done in a session of the House by one of its members in relation to the business before it."  Id. at 204.  The Court noted that it did not need to decide the limits of the clause, or the types of things that a member of the House or Senate might do for which they could be held legally responsible.  Id.  It did, however, reject the idea that "the constitutional provision for freedom of debate" would "screen[] from punishment" "an utter perversion of [legislators''] powers to a criminal purpose."  Id. at 205.

            In United States v. Johnson, 383 U.S. 169 (1966), the Court considered the case of a former member of the United States Congress who was indicted and convicted of violating the Federal conflict of interest statute, 18 U.S.C. § 281, and conspiring to defraud the United States, 18 U.S.C. § 371.  A key fact upon which the prosecution rested was that Johnson, in exchange for compensation, made a speech on the floor of the House defending the operations of certain savings and loans associations.  Id. at 184.  The Court held that "a prosecution under a general criminal statute dependent on such inquiries necessarily contravenes the Speech or Debate Clause," but "emphasize[d] that [its] holding is limited to prosecutions involving circumstances such as those presented in the case before us" -- namely, a speech on the floor of the House.  Id. at 184-185.  The Court also expressly left "open for consideration when the case arises a prosecution which, though possibly entailing inquiry into legislative acts or motivations, is founded upon a narrowly drawn statute passed by Congress in the exercise of its legislative power to regulate the conduct of its members."  Id. at 185.

            The Court next considered the clause in Gravel v. United States, 408 U.S. 606 (1972), which involved a United States senator who read extensive portions of the Pentagon Papers (study) during a subcommittee meeting and placed the entire study in the public record.  A member of the senator''s staff assisted Gravel in preparing for and conducting the hearing.  Id. at 609.  The senator also was alleged to have made an arrangement with a private press to publish the study.  Id. at 609-610.  The Court concluded that the senator''s alleged arrangement with the press was not protected by the clause, but that his conduct during the subcommittee meeting was.  Id. at 616, 622.  It also concluded that the clause extended to the senator''s aide to the same extent as it extended to the senator.  Id. at 616.  In reaching these conclusions, the Court spelled out that the clause does not extend beyond the "legislative sphere."  Id. at 624-625.  And the fact that senators "perform certain acts in their official capacity as Senators does not necessarily make all such acts legislative in nature."  Id. at 625.  Instead, acts protected by the clause "must be an integral part of the deliberative and communicative processes by which Members participate in committee and House proceedings with respect to the consideration and passage or rejection of proposed legislation or with respect to other matters which the Constitution places within the jurisdiction of either House."  Id.  The Court also emphasized that the clause

"does not purport to confer a general exemption upon Members of Congress from liability or process in criminal cases.  Quite the contrary is true.  While the Speech or Debate Clause recognizes speech, voting, and other legislative acts as exempt from liability that might otherwise attach, it does not privilege either Senator or aide to violate an otherwise valid criminal law in preparing for implementing legislative acts."

Id. at 626.

            That same term, the Court considered and decided the case of United States v. Brewster, 408 U.S. 501 (1972), which involved a senator who was charged with violating 18 U.S.C. §§ 201(c)(1), 201(g), by accepting a bribe in exchange for a promise relating to an official act.  After reviewing its previous cases, the Court held that a "Member of Congress may be prosecuted under a criminal statute provided that the Government''s case does not rely on legislative acts or the motivation for legislative acts."  Id. at 512.  It defined a "legislative act" as one "generally done in Congress in relation to the business before it."  Id.  Put otherwise, the clause is "limited to an act which was clearly a part of the legislative process -- the due functioning of the process."  Id. at 515-516.  The Court acknowledged that members of Congress engage in many legitimate activities, but drew a distinction between "legitimate," but "political" activities -- which are not protected by the clause -- and "legislative" ones -- which are.[11]  Id. at 512-513.  At bottom, the Court concluded that the clause "does not extend beyond what is necessary to preserve the integrity of the legislative process."  Id. at 517.

            The Court next returned to the clause in Hutchinson v. Proxmire, 443 U.S. 111 (1979), a defamation suit brought against a senator based on statements he included in press releases, a television interview, and newsletters to constituents concerning a research director and professor in Michigan.  Repeating its previous explications of the scope of the clause, the Court concluded that transmittal of information by individual members in order to inform the public "is not a part of the legislative function or the deliberations that make up the legislative process."  Id. at 133.

            Most recently, the Court considered the clause in United States v. Gillock, 445 U.S. 360 (1980), and concluded that the clause does provide protection to State legislators from Federal prosecution.  See note 2, supra.

            With this survey in hand, we now return to art. 21 and the specifics of this case.  As we have already noted, the defendant has been indicted for using his Senate staff to conduct campaign activities during work hours while being paid out of the public fisc.  The defendant himself acknowledges "[t]he most important acts alleged in the indictment[s] is [sic] the misuse of legislative aides."  But he goes on to assert that "the direction of legislative aides is a fundamental legislative act" and, therefore, under art. 21 he is immune from prosecution.  We disagree.

            As one commentator has explained,

"[T]he [C]ourt in [Coffin] interposed a condition precedent to the exercise of legislative privilege, that is, the official conduct or official duties test.  To be entitled to the claim of privilege a legislator must first prove to the satisfaction of the court that his language or conduct is ''in the character of a representative'' -- i.e., in the execution of his official duties as a legislator."

Cella, The Doctrine of Legislative Privilege of Freedom of Speech and Debate:  Its Past, Present and Future as a Bar to Criminal Prosecution in the Courts, 2 Suffolk U. L. Rev. 1, 28 (1968).  The conduct described in the indictments clearly does not rest on, or in any way implicate, the defendant''s duties as a legislator.  See Brewster, 408 U.S. at 525 (looking to face of indictment to determine whether prosecution requires inquiry into legislative acts).  The defendant does not assert, for example, that the conduct he is alleged to have engaged in took place on the floor, or in committee, or in connection with legislation, or in connection with a matter under deliberation by the Senate.  See Cachopa v. Stoughton, 72 Mass. App. Ct. 657, 666 (2008) (nonlegislative actions regarding employment of police chief not immune under art. 21).  Indeed, there is no contention whatsoever -- let alone showing -- that the indictments rest on any activity or speech connected with the business of the Senate. 

            Instead, the indictments are based on alleged campaign activities, which are political rather than legislative in nature.  See Brewster, 408 U.S. at 512 (nonlegislative acts include "political" acts performed as "a means of developing continuing support for future elections").  The indictments also charge the defendant with misuse of public resources, including the defendant''s Senate staff.  But the use of legislative aides to carry out nonlegislative tasks is self-evidently not legislative activity.  See Floyd v. Lee, 968 F. Supp. 2d 308, 322 (D.D.C. 2013) ("decisions to assign non-legislative work to legislative aides" are not "protected legislative acts").  See also Gravel, 408 U.S. at 618 (conduct of legislative aides only protected "insofar as the conduct . . . would be a protected legislative act if performed by the Member himself").  And, along the same lines, the misuse of other types of public resources for nonlegislative activities is also outside the scope of art. 21.  See Brewster, 408 U.S. 501, 522 n.16, citing United States v. Bramblett, 348 U.S. 503 (1955) (no absolute immunity from criminal prosecution for "Congressman''s misuse of office funds via a ''kick-back'' scheme"); United States ex rel. Hollander v. Clay, 420 F. Supp. 853, 856 (D.D.C. 1976) (filing false vouchers to obtain reimbursement for travel to congressional district not protected legislative act).

            In the circumstances, we have no difficulty concluding that the freedom of legislative deliberation, speech, and debate contained in art. 21 does not provide the defendant with immunity from prosecution under the conflict of interest statute.

            b.  Separation of powers.  Relying on arts. 10 and 11, the defendant contends that the indictments impermissibly interfere with the Senate''s authority and, thus, violate the separation of powers.

            Article 10, by its own terms, is limited to the House of Representatives, of which the defendant was not a member.  For this reason, the defendant cannot rely on art. 10 directly, but rather must depend on the first paragraph of art. 11, which incorporates art. 10 by reference and provides that "[t]he senate shall have the same powers in the like cases" (emphasis added).  Through the first paragraph of art. 11, the Senate is given exclusive authority over the same matters conferred to the exclusive authority of the House of Representatives in art. 10, namely, the authority to "be the judge of the returns, elections, and qualifications of its own members, as pointed out in the [C]onstitution; [to] choose their own speaker; [to] appoint their own officers, and [to] settle the rules and orders of proceeding in their own house."  See Coffin, 4 Mass. at 7 (each chamber has exclusive authority to "judge [its own] rules and orders, enforce their observance, and punish a member for any violation of them").

            Because the authority under art. 10 and, by incorporation, the first paragraph of art. 11, is exclusive, we have, for example, rejected an attempt to use an initiative petition pursuant to art. 48 of the Amendments to the Massachusetts Constitution to intrude on the internal operations of the House or Senate.  Paisner v. Attorney Gen., 390 Mass. 593, 599-600 (1983).  Similarly, we have rejected the Legislature''s attempt to delegate to the judicial branch its exclusive art. 10 authority.  Dinan v. Swig, 223 Mass. 516, 516, 520 (1916) (rejecting statute designed to permit five or more voters to petition Superior Court to investigate allegation of corruption in election of candidate to either house).  "The power to pass upon the election and qualification of its own members . . . is vested exclusively in each branch of the General Court."  Id. at 517. 

            In contrast to the first paragraph of art. 11, which confers exclusive authority, the second paragraph of art. 11 confers only nonexclusive authority because -- unlike the first paragraph, which uses the word "shall" -- the second paragraph provides only that each house "may try, and determine, all cases where their rights and privileges are concerned" (emphasis added).  This is an important distinction, and the difference between the plain meaning of "shall" and "may" is the reason why the authority conferred under the first paragraph of art. 11 is exclusive, while the authority under the second paragraph is not. 

            We have only once examined the second paragraph of art. 11 and have concluded that the nonexclusive power to "try, and determine, all cases where [the members''] rights and privileges are concerned" carries with it the necessary and incidental power to expel a member from the House.  Hiss v. Bartlett, 3 Gray 468, 473 (1855).  But the implied power of each house to discipline or expel a member under the second paragraph of art. 11 does not displace the authority of the executive branch to indict, or the power of the judiciary to try, a member for a violation of a criminal statute.  See id. ("Impeachment lies only for purposes of punishment, by deprivation of office, and disqualification to hold office, leaving the offender still liable to indictment, if the offence be indictable").  Nor does each house''s unicameral power under the second paragraph of art. 11 displace the bicameral authority of the Legislature to define criminal conduct or prescribe penalties for it.  "The Legislature has great latitude in defining criminal conduct and in prescribing penalties to vindicate the legitimate interests of society."  Commonwealth v. Pyles, 423 Mass. 717, 721 (1996) (judge''s disposition of case consistent with statute does not violate separation of powers).

            It should be apparent from what we have just said that the defendant''s reliance on arts. 10 and 11 fails for several reasons.  The defendant faces criminal liability for having violated the State conflict of interest law.  He is not charged with having violated the Senate''s internal rules or procedures, nor do the indictments rest on election irregularities or his qualifications for office.  As a result, the indictments do not implicate any matter within the exclusive authority of the Senate under the first paragraph of art. 11.  See Coffin, 4 Mass. at 7.

            The analysis with respect to the second paragraph of art. 11 is slightly different.  Under the second paragraph, the Senate has the authority to "try, and determine, all cases where [the members''] rights and privileges are concerned."  Because the Senate''s unicameral authority under the second paragraph is not exclusive, it does not displace the bicameral authority of the Legislature to criminalize the defendant''s misuse of his staff, nor does it displace the authority of the executive branch to charge the defendant for a violation of a criminal law, nor does it displace the authority of the courts to hear and impose sentence on the conviction of such criminal charges. 

            For these reasons, the defendant is not immune from prosecution under separation of powers principles reflected in arts. 10 and 11.

            3.  Exclusion of a grand juror.  The defendant argues that the integrity of the grand jury process was impaired because the prosecutor excluded a grand juror from deliberating and voting on the indictments and, therefore, the indictments should be dismissed.  Our review is de novo.  See Commonwealth v. Barlow-Tucker, 493 Mass. 197, 204 (2024). 

            The grand jury proceedings took place over several months in 2023.  On September 21, 2023, one of the witnesses made reference to the defendant''s friendship with "the leader of [a] group of Trump supporters."  In response to this testimony, a grand juror asked the witness to rate "how on a scale of . . . one to five, was [the defendant] a big supporter of the controversial and now disgraced once [P]resident."  The prosecutor interrupted to "stop that question," and noted that it was "not relevant to this investigation." 

            One week later, when the case was next before the grand jury, the prosecutor took the grand juror aside and spoke to him on the record, but outside the presence of the other jurors.  The prosecutor asked whether the grand juror had any biases that would "affect [his] ability to be fair and impartial," and he responded that he would "[a]bsolutely not" have a problem being impartial, but he was "concerned . . . that the subject of the case is about politics."  During further discussion, the juror stated that "we all have biases."

            After this exchange, the prosecutor read the following statement into the record, out of the presence of the grand jurors:

"A few minutes ago, I pulled a juror aside who asked a question on September 21, 2023 that appeared to draw a connection between [the defendant] and a former President.  The question seemed to indicate a potential bias against that former President and appeared to draw a negative connotation related to any potential connection real or imagined between the former President and [the defendant].  I instructed the juror that asked the question that the political affiliations of any of the individuals involved in this investigation were not relevant to the determination of probable cause, and were inappropriate to consider.  I asked the juror to the extent that he had any potential biases against any of the individuals . . . for their possible political affiliations, whether he would be able to set those biases aside and vote fairly and impartially in the testimony and evidence put before him related to the charges he would be called upon to vote.  He replied repeatedly that he could.  However, I pushed back - he pushed back on the instruction that the political affiliations were not relevant and said that he believed the case is political in nature and that he was trying to objectively view the politics involved.  When instructed again that the only relevant consideration was whether there was probable cause[] for any potential charges put before him, he continued to push back and attempted to talk over my instructions.  His attitude conveyed a disinterest in accepting the instruction on its face, understanding that the ultimate question was whether he could set aside his possible biases and he stated that he could.  It is my position based on his attitude and further discussion that he is not in fact able to judge the merits of this case impartially and I am instructing the juror not to participate and vote on this matter."

The prosecutor then instructed the grand juror to remain in a separate room while the other grand jurors proceeded to vote on the indictments.

            As we have already said, the defendant argues that the indictments should be dismissed because the prosecutor''s action in excluding the grand juror impaired the integrity of the grand jury.  He further asserts that the grand juror''s exclusion constituted a "structural" defect requiring dismissal without a showing of prejudice.  Structural errors, which "have been recognized in limited circumstances" and "occur rarely," Commonwealth v. Hampton, 457 Mass. 152, 163 (2010), are "constitutional error[s] of the first magnitude," Commonwealth v. Francis, 485 Mass. 86, 100 (2020), cert. denied, 141 S. Ct. 2762 (2021), quoting Commonwealth v. Valentin, 470 Mass. 186, 196 (2014).  The defendant, however, was not constitutionally entitled to a grand jury that included the excluded grand juror.  See Commonwealth v. Wilcox, 437 Mass. 33, 37 (2002) (grand jury "can continue functioning despite absent members").  There was accordingly no structural defect in the proceedings here.

            Because there was no structural defect, the defendant was required to show that he was prejudiced by the exclusion of the grand juror.  See Commonwealth v. Mathews, 450 Mass. 858, 874 (2008), quoting Commonwealth v. King, 400 Mass. 283, 290 (1987) ("we have never ordered the dismissal of an indictment for [prosecutorial] misconduct in the absence of prejudice").  No prejudice appears here.  In contrast to the verdict of a petit jury, the decision of a grand jury need not be unanimous.  Instead, only "twelve or more" of the jurors must concur in the decision to return an indictment, with at least thirteen of the grand jurors present for the vote.  Mass. R. Crim. P. 5 (e), 365 Mass. 745 (1974).  The defendant makes no contention that these requirements were not met.  As a result, he has failed to show that the vote of the excused grand juror would have made a difference in the grand jury''s decision to return the indictments.  See id.  See also Commonwealth v. Freeman, 407 Mass. 279, 283 (1990), quoting Commonwealth v. Mayfield, 398 Mass. 615, 621-622 (1986) (dismissal of indictment not warranted where defendant failed to show that improper statements to grand jury "''probably made a difference'' in their decision to indict him").  Moreover, the excluded grand juror had expressed political views arguably reflecting a bias against the defendant and, therefore, excluding the grand juror was protective of the defendant''s interests.  Cf. Commonwealth v. Roman, 470 Mass. 85, 87 n.1 (2014) (defendant not prejudiced where improper evidence "buttress[ed] his theory").  Accordingly, the judge was correct to deny the defendant''s motion to dismiss the indictments on the ground that the defendant failed to show any prejudice flowing from the exclusion of the grand juror.

            That said, we take this opportunity to give guidance to prosecutors who become aware of information indicating that a grand juror harbors a bias against a person against whom the grand jury are considering bringing criminal charges.  "[U]nlike petit jurors, grand jurors may act on their own personal knowledge and need not be free from all bias or prejudice."  Commonwealth v. McLeod, 394 Mass. 727, 733, cert. denied sub nom. Aiello v. Massachusetts, 474 U.S. 919 (1985).  This is because "the safeguards deemed necessary to protect an accused before a petit jury are not implicated to the same degree in grand jury proceedings" given "the historical and practical nature of the grand jury, and the availability of an unprejudiced petit jury at trial."  Id.  However, grand jurors "must act in a matter consistent with their oath," id., which requires that they "shall present no man for envy, hatred or malice," G. L. c. 277, § 5.  We have said that "further inquiry may be warranted where [there is] a prima facie showing of bias or prejudice so egregious as to result in an indictment based on ''hatred or malice,'' within the meaning of G. L. c. 277, § 5."  McLeod, 394 Mass. at 734.  Where a prosecutor becomes concerned that a grand juror harbors bias or prejudice of this magnitude, she or he should bring the matter to the attention of the judge for further inquiry and, if appropriate, action.

            The prosecutor should not exclude or excuse a grand juror for bias without judicial involvement.  Such a decision belongs to the court because the grand jury "are an appendage, a branch, an integral part of the court acting under the authority of the court," Grand Jurors for Worcester County for the Year 1951 v. Commissioner of Corps. & Taxation, 329 Mass. 89, 91 (1952), and because the court has "discretionary authority to dismiss a juror at any time in the best interests of justice."  G. L. c. 234A, § 39.  See Commonwealth v. Martinez, 420 Mass. 622, 625 (1995), abrogated on other grounds by Commonwealth v. Azar, 435 Mass. 675 (2002) ("Courts have the authority to supervise grand jury proceedings to ensure the effective administration of justice").  Contrast Alaska R. Crim. P. 6(t)(1) ("The prosecutor shall excuse a juror for a particular case when the juror informs the prosecutor that the juror cannot be fair or impartial in deciding that case").  The prosecutor''s role in grand jury proceedings, while not strictly circumscribed, is not unbounded.  Cf. Commonwealth v. Smith, 414 Mass. 437, 441 (1993) (prosecutor "cannot participate in the deliberations or express opinions on questions of fact or attempt in any way to influence the action").  The prosecutor''s authority does not extend to deciding whether a particular grand juror is biased against the defendant to such a degree that the grand juror should be excluded from considering whether to return an indictment against the defendant.

            While the prosecutor has latitude to proceed when a grand juror is absent for routine reasons such as a medical appointment, or to attend a funeral, excusing a grand juror for bias stands on a different footing from neutral scheduling conflicts.  Excusing a grand juror on the basis of bias necessarily entails a careful and delicate inquiry into a grand juror''s views that is best left to the supervising judge.  Cf. Commonwealth v. Tavares, 385 Mass. 140, 156, cert. denied, 457 U.S. 1137 (1982) (judge in best position to determine whether petit juror was impartial).  For all these reasons, a prosecutor who becomes concerned that a grand juror holds a bias so egregious as to result in an indictment based on "hatred or malice" should take the matter to the supervising judge for inquiry and decision.

            Conclusion.  The Superior Court judge was correct to deny the defendant''s motion to dismiss, and we remand this case to the county court for entry of a judgment denying the petition for relief under G. L. c. 211, § 3.

So ordered.

 

footnotes

 

            [1] Although Dean Tran commenced this action by filing a petition in the county court, for convenience we refer to him as the "defendant."

            [2] The petition also pressed two additional claims.  First, the defendant argued that the indictments violate the defendant''s right against double jeopardy given prior disciplinary proceedings in the Senate.  But the defendant no longer presses this argument, so we do not consider it.  Mass. R. A. P. 16 (a) (9) (A), as appearing in 481 Mass. 1628 (2019) ("The appellate court need not pass upon questions or issues not argued in the brief").

            Second, the defendant argued that he is entitled to legislative immunity under the speech or debate clause of art. I, § 6, of the United States Constitution.  The defendant''s briefing to the full court does not clearly articulate whether he continues to rely on the Federal clause for his claim of legislative immunity.  Setting aside the ambiguity of the defendant''s briefing, "by its terms," the Federal speech or debate clause "is confined to federal legislators" and does not apply to State legislators like the defendant.  United States v. Gillock, 445 U.S. 360, 374 (1980).  See infra at    . 

            [3] In the motion to dismiss, the defendant also argued that he should have been charged with only a misdemeanor violation of the campaign finance law, G. L. c. 55, and therefore the Superior Court did not have jurisdiction, and that double jeopardy principles precluded the indictments.  The defendant does not press these arguments now, and we do not consider them.

            [4] Because the single justice reported the entire matter to us, we do not consider whether the defendant''s argument based on the exclusion of the grand juror would have been entitled -- had it been standing alone -- to interlocutory review under G. L. c. 211, § 3.  See Cabrera v. Commonwealth, 496 Mass. 179, 183 (2025) (reaching merits of claim raised on interlocutory appeal without deciding whether standard for relief under G. L. c. 211, § 3, was met "[b]ecause the single justice reserved and reported the interlocutory appeal to the full court"); Commonwealth v. Arrington, 493 Mass. 478, 489 (2024) ("Because this case was reserved and reported by the single justice, we need not decide whether the case meets the standard for relief under G. L. c. 211, § 3").

            [5] The defendant suggests that the claim be filed in the first instance with a single justice of the Appeals Court, who would then direct it to a panel of that court.

            [6] See, e.g., Lynch v. Crawford, 483 Mass. 631, 640-641 (2019) (order denying charitable immunity from suit to recover unpaid wages); Edwards v. Commonwealth, 477 Mass. 254, 260 n.8 (2017), S.C., 488 Mass. 555 (2021) (order denying Governor''s motion to dismiss defamation claims on ground that challenged statements were protected by absolute and qualified privilege); Estate of Moulton v. Puopolo, 467 Mass. 478, 485-486 (2014) (order denying employers statutory immunity under exclusive remedy provision, G. L. c. 152, § 24, of workers'' compensation act from wrongful death suit); Maxwell v. AIG Domestic Claims, Inc., 460 Mass. 91, 92, 98 (2011) (order denying insurer statutory immunity from suit for malicious prosecution, infliction of emotional distress, and abuse of process); Boxford v. Massachusetts Highway Dep''t, 458 Mass. 596, 601 (2010) (order denying sovereign immunity from suit seeking to enjoin certain activities of State Highway Department); Kent v. Commonwealth, 437 Mass. 312, 316 (2002) (order denying Commonwealth immunity under Tort Claims Act, G. L. c. 258, § 10 [j]); Breault v. Chairman of the Bd. of Fire Comm''rs of Springfield, 401 Mass. 26, 31 (1987), cert. denied sub nom. Forastiere v. Breault, 485 U.S. 906 (1988) (order denying qualified immunity from suit brought under 42 U.S.C. § 1983); Abuzahra v. Cambridge, 101 Mass. App. Ct. 267, 269-271 (2022) (discovery order in civil suit denying legislative privilege with respect to communications involving city councillors and councillors'' aides).

            [7] In full, the first indictment alleges the following:

"Beginning on or about January 1, 2018, and continuing to on or about November 6, 2018, being a current officer or employee of a [S]tate agency, knowingly, or with reason to know, and with fraudulent intent, did use or attempt to use such official position to secure for himself or others unwarranted privileges or exemptions of substantial value which were not properly available to similarly situated individuals, to wit:  did utilize public resources, including members of his Massachusetts State Senate staff, for his 2018 campaign for re-election as the State Senator for the Worcester and Middlesex District, which unwarranted privilege or exemption had a fair market value in the aggregate of more than $1,000 in any 12-month period, in violation of [G. L. c. 268A, §§ 23 (b) (2) (ii) and 26]."

The second indictment is substantially the same, but pertains to conduct "[b]eginning on or about January 1, 2019, and continuing to on or about October 31, 2019," related to the defendant''s 2020 campaign for reelection.

            [8] "The senate shall have the same powers in the like cases; and the governor and council shall have the same authority to punish in like cases.  Provided that no imprisonment on the warrant or order of the governor, council, senate, or house of representatives, for either of the above described offences, be for a term exceeding thirty days."  Part II, c. 1, § 3, art. 11.

            [9] The defendant also argues that the indictments rest impermissibly on communications and testimony subject to legislative privilege.  As an initial matter, we note that although the defendant raised this argument in his G. L. c. 211, § 3, petition, it was not raised in his motion to dismiss.  See Mass. R. Crim. P. 13 (a) (2), as appearing in 442 Mass. 1516 (2004).  Setting aside the question of waiver, the argument fails for two reasons.  First, the defendant does not identify specific testimony or exhibits upon which his claims of privilege are founded.  See United States v. Renzi, 651 F.3d 1012, 1030 (9th Cir. 2011), cert. denied, 565 U.S. 1157 (2012) (incumbent on defendant claiming legislative privilege to "bring to [court'']s attention those specific exhibits that cause him concern").  The defendant''s assertions, made without citation to the record, therefore do not rise to the level of appellate advocacy.  See Mass. R. A. P. 16 (a) (9) (A).  Cf. Adoption of Saul, 60 Mass. App. Ct. 546, 554 (2004) (privilege claims made "without citation to the record identifying the communications or the basis for the claims of privilege" disposed of "without in-depth discussion").  Second, there is nothing in the record to suggest that the defendant''s communications with his staff were made in connection with his duties as a legislator.  Thus, as presented, any claim of privilege would fail for the same reasons as his claim of immunity.  See Gravel v. United States, 408 U.S. 606, 616 (1972) (Federal speech and debate clause "prohibits inquiry into things done by" member of senator''s staff "which would have been legislative acts, and therefore privileged" [citation omitted]).

            [10] The speech or debate clause of art. I, § 6, of the United States Constitution provides:  "The Senators and Representatives shall . . . be privileged . . . for any Speech or Debate in either House, they shall not be questioned in any other Place."  Cf. Huefner, The Neglected Value of the Legislative Privilege in State Legislatures, 45 Wm. & Mary L. Rev. 221, 236 n.51 (2003) ("Both because of [art. 21'']s explicit inclusion of legislative ''deliberation'' among the protected activities, and because of its inclusive list of the types of prohibited judicial inquiry, this formulation arguably could admit of a broader construction than that of the federal Speech or Debate Clause.  But in fact, the federal clause has been interpreted with an equally broad scope").

            [11]

"It is well known, of course, that Members of the Congress engage in many activities other than the purely legislative activities protected by the Speech or Debate Clause.  These include a wide range of legitimate ''errands'' performed for constituents, the making of appointments with Government agencies, assistance in securing Government contracts, preparing so-called ''news letters'' to constituents, news releases, and speeches delivered outside the Congress.  The range of these related activities has grown over the years.  They are performed in part because they have come to be expected by constituents, and because they are a means of developing continuing support for future elections.  Although these are entirely legitimate activities, they are political in nature rather than legislative, in the sense that term has been used by the Court in prior cases."

Brewster, 408 U.S. at 512.$OPINION_TEXT$,
    'https://www.courtlistener.com/opinion/10669207/dean-tran-v-commonwealth/?q=&court_texdistct142=on&order_by=score+desc&page=2#o1',
    'Budd, C.J., Gaziano, Kafker, Wendlandt, Georges, & Wolohojian, JJ.',
    'Criminal',
    'General Court. Constitutional Law, General Court, Separation of powers. Practice, Criminal, Immunity from prosecution, Conduct of prosecutor, Interlocutory appeal, Grand jury proceedings, Dismissal. Conflict of Interest. Grand Jury. Supreme Judicial Court, Superintendence of inferior courts.',
    'courtlistener',
    'https://www.courtlistener.com/opinion/10669207/dean-tran-v-commonwealth/?q=&court_texdistct142=on&order_by=score+desc&page=2#o1',
    TRUE,
    TRUE
);

-- Verify the insertion
SELECT id, case_name, docket_number, court_type, decision_date 
FROM court_cases 
WHERE case_name = 'DEAN TRAN vs. COMMONWEALTH';
